name: Compile on Ubuntu

on:
  push:
    paths-ignore:
    - '**.md'
    branches-ignore: [snapshot]
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  linux:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.8.1
        arch: linux_gcc_64
        modules: ''
        tools: 'tools_qtcreator'
        setup-python: false
        cache: true

    - name: Install dependencies
      run: |
        sudo apt-get install libgl1-mesa-dev libxcursor-dev libxi-dev

    - name: Build
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release --target qaseprite
